ansible_python_interpreter: /usr/bin/python3

kubernetes:
  clusterName: podspace-pardis-01
  etcdVersion: v3.5.12
  crictlVersion: v1.29.0
  runcVersion: v1.1.12
  containerdVersion: v1.7.13
  cniVersion: v1.4.0
  version: v1.29.1
  # manifests:
  #   dir: /opt/kube-ansible/manifests

  certificate:
    directory: /home/{{ ansible_ssh_user }}/kube-ansible/certs

  encryptionProvider:
    key: Wrc71ysY7XogUdoMydyuoHZjkgKFAuK5ViwxcnJ17uk=
  bin:
    directory: /home/{{ ansible_ssh_user }}/kube-ansible/files

pki:
  ca:
    expireTime: 175200h
    certificate:
      expireTime: 8760h
    city: Tehran
    country: IR
    organizationUnit: Podspace
    province: Tehran

