---
- name: Copy kubeconfigs into worker nodes
  shell: |
    scp -o StrictHostKeyChecking=no {{ item }}.kubeconfig kube-proxy.kubeconfig {{ ansible_ssh_user }}@{{ hostvars[item].ansible_host }}:~/
  with_items: "{{ groups['worker'] }}"
  args:
    chdir: "{{ kubernetes.certificate.directory }}"

- name: Copy kubeconfigs into controller nodes
  shell: |
    scp -o StrictHostKeyChecking=no admin.kubeconfig kube-controller-manager.kubeconfig kube-scheduler.kubeconfig {{ ansible_ssh_user }}@{{ hostvars[item].ansible_host }}:~/
  with_items: "{{ groups['controller'] }}"
  args:
    chdir: "{{ kubernetes.certificate.directory }}"
