- name: Deployer preparation
  become: yes
  gather_facts: no
  hosts: deployer
  roles:
    - pre 
  tags:
    - pre

- name: Generate certificates
  gather_facts: no
  hosts: deployer
  roles:
    - certificate-ca
  tags:
    - create-certs

- name: Copy certificates
  gather_facts: no
  hosts: deployer
  roles:
    - copy-certs
  tags:
    - copy-certs

- name: Generate kubeconfigs
  gather_facts: no
  hosts: deployer
  roles:
    - kubeconfig
  tags:
    - kubeconfig

- name: Copy kubeconfigs
  gather_facts: no
  hosts: deployer
  roles:
    - copy-kubeconfig
  tags:
    - copy-kubeconfig

- name: Copy binaries to nodes
  gather_facts: no
  become: yes
  hosts: deployer
  roles:
    - copy-bin
  tags:
    - copy-bin

- name: Create etcd cluster
  become: yes
  hosts: etcd
  roles:
    - etcd
  tags:
    - etcd

- name: Setup controller cluster
  become: yes
  hosts: controller
  roles:
    - controller
  tags:
    - controller

- name: Setup worker nodes
  become: yes
  hosts: worker
  roles:
    - worker
  tags:
    - worker

- name: Setup CNI & DNS
  become: yes
  hosts: controller
  roles:
    - addons
  tags:
    - addons
