- name: Deployer preparation
  become: yes
  hosts: deployer
  connection: local
  roles:
    - pre 
  tags:
    - pre

- name: Generate certificate & kubeconfig
  become: yes
  hosts: deployer
  connection: local
  roles:
    - certificate-ca
    - kubeconfig
  tags:
    - cert-config

- name: Copy binaries to nodes
  become: yes
  hosts: deployer
  connection: local
  roles:
    - copy-bin
  tags:
    - copy-bin

- name: Create etcd cluster
  become: yes
  hosts: etcd
  roles:
    - etcd
  tags:
    - etcd

- name: Setup controller cluster
  become: yes
  hosts: controller
  roles:
    - controller
  tags:
    - controller

- name: Setup worker nodes
  become: yes
  hosts: worker
  roles:
    - worker
  tags:
    - worker

- name: Setup CNI & DNS
  become: yes
  hosts: controller
  roles:
    - addons
  tags:
    - addons
