---
- name: Copy controller binaries to controller nodes
  vars:
    controllers: "{{ groups['controller'] | join(' ') }}"
  shell: |
    for instance in {{ controllers }}; do
      scp files/{{ kubernetes.version }}/kube-apiserver {{ user }}@${instance}:/usr/local/bin
      scp files/{{ kubernetes.version }}/kube-controller-manager {{ user }}@${instance}:/usr/local/bin
      scp files/{{ kubernetes.version }}/kube-scheduler {{ user }}@${instance}:/usr/local/bin
      scp files/{{ kubernetes.version }}/kubectl {{ user }}@${instance}:/usr/local/bin
    done
  tags:
    - controller-bin
