---
- name: Copy controller binaries to controller nodes
  shell: |
    rsync -avz -e "ssh -o StrictHostKeyChecking=no" {{ kubernetes.bin.directory }}/{{ kubernetes.version }}/kube-apiserver {{ ansible_ssh_user }}@{{ hostvars[item].ansible_host }}:/tmp/{{ kubernetes.version }}/
    rsync -avz -e "ssh -o StrictHostKeyChecking=no" {{ kubernetes.bin.directory }}/{{ kubernetes.version }}/kube-controller-manager {{ ansible_ssh_user }}@{{ hostvars[item].ansible_host }}:/tmp/{{ kubernetes.version }}/
    rsync -avz -e "ssh -o StrictHostKeyChecking=no" {{ kubernetes.bin.directory }}/{{ kubernetes.version }}/kube-scheduler {{ ansible_ssh_user }}@{{ hostvars[item].ansible_host }}:/tmp/{{ kubernetes.version }}/
    rsync -avz -e "ssh -o StrictHostKeyChecking=no" {{ kubernetes.bin.directory }}/{{ kubernetes.version }}/kubectl {{ ansible_ssh_user }}@{{ hostvars[item].ansible_host }}:/tmp/{{ kubernetes.version }}/
  with_items: "{{ groups['controller'] }}"
  args:
    chdir: "{{ kubernetes.certificate.directory }}"
  tags:
    - controller-bin
