---
- name: Copy etcd binaries to etcd nodes
  shell: |
    rsync -avz -e "ssh -o StrictHostKeyChecking=no" {{ kubernetes.bin.directory }}/etcd-{{ kubernetes.etcdVersion }}/etcd* {{ ansible_ssh_user }}@{{ hostvars[item].ansible_host }}:/tmp/etcd-{{ kubernetes.etcdVersion }}
  with_items: "{{ groups['worker'] }}"
  args:
    chdir: "{{ kubernetes.certificate.directory }}"
  tags:
    - etcd-bin
