---
- name: Copy worker binaries to worker nodes
  vars:
    workers: "{{ groups['worker'] | join(' ') }}"
  shell: |
    for instance in {{ workers }}; do
      scp files/{{ kubernetes.version }}/crictl {{ user }}@${instance}:/usr/local/bin
      scp files/{{ kubernetes.version }}/kubectl {{ user }}@${instance}:/usr/local/bin
      scp files/{{ kubernetes.version }}/kube-proxy {{ user }}@${instance}:/usr/local/bin
      scp files/{{ kubernetes.version }}/kubelet {{ user }}@${instance}:/usr/local/bin
      scp files/{{ kubernetes.version }}/runc {{ user }}@${instance}:/usr/local/bin
      scp files/{{ kubernetes.version }}/containerd/bin/* {{ user }}@${instance}:/bin
      rsync -a --mkpath files/{{ kubernetes.version }}/cni/* {{ user }}@${instance}:/opt/cni/bin
    done
  tags:
    - worker-bin
