---
- name: Copy worker binaries to worker nodes
  vars:
    workers: "{{ groups['worker'] | join(' ') }}"
  shell: |
    for instance in {{ workers }}; do
      scp files/v1.25.13/crictl {{ user }}@${instance}:/usr/local/bin
      scp files/v1.25.13/kubectl {{ user }}@${instance}:/usr/local/bin
      scp files/v1.25.13/kube-proxy {{ user }}@${instance}:/usr/local/bin
      scp files/v1.25.13/kubelet {{ user }}@${instance}:/usr/local/bin
      scp files/v1.25.13/runc {{ user }}@${instance}:/usr/local/bin
      scp files/v1.25.13/containerd/bin/* {{ user }}@${instance}:/bin
      rsync -a --mkpath files/v1.25.13/cni/* {{ user }}@${instance}:/opt/cni/bin
    done
  tags:
    - worker-bin
