all:
  hosts:
    appsdfpspsd0101:
      ansible_host: 192.168.115.61
      loadbalancer:
      # external_ip: 95.217.0.11
    # kube02:
    #   ansible_host: 192.168.20.3
    #   external_ip: 167.235.65.67
    # kube03:
    #   ansible_host: 192.168.20.4
    #   external_ip: 128.140.33.136
    # kube04:
    #   ansible_host: 192.168.20.5
    #   external_ip: 65.109.239.95
    deployer:
      ansible_host: 192.168.115.61
  children:
    etcd:
      hosts:
        appsdfpspsd0101:
    controller:
      hosts:
        appsdfpspsd0101:
    worker:
      hosts:
        appsdfpspsd0101: