- name: Copy worker binaries to worker nodes
  shell: |
    rsync --chmod=700 "{{ kubernetes.bin.directory }}/{{ kubernetes.version }}/kubelet" "{{ user }}@{{ inventory_hostname }}:/usr/local/bin"
    rsync --chmod=700 "{{ kubernetes.bin.directory }}/{{ kubernetes.version }}/kube-proxy" "{{ user }}@{{ inventory_hostname }}:/usr/local/bin"
    rsync --chmod=700 "{{ kubernetes.bin.directory }}/{{ kubernetes.version }}/kubectl" "{{ user }}@{{ inventory_hostname }}:/usr/local/bin"
  delegate_to: deployer
