---
- name: Change permissions of bin files
  file:
    path: /usr/local/bin
    recurse: yes 
    mode: '0700'

- name: Create /var/lib/kubernetes/ & /etc/kubernetes/config directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - /var/lib/kubernetes/
    - /etc/kubernetes/config

- name: Copy certs to /var/lib/kubernetes/
  copy:
    src: "{{ item }}"
    dest: /var/lib/kubernetes/
  with_items:
    - ~/ca.pem
    - ~/ca-key.pem
    - ~/kubernetes-key.pem
    - ~/kubernetes.pem
    - ~/service-account-key.pem
    - ~/service-account.pem
    - ~/encryption-config.yaml
    - ~/kube-controller-manager.kubeconfig
    - ~/kube-scheduler.kubeconfig

- name: Create Kubernetes API Server systemd unit file
  template:
    src: kube-apiserver.service.j2 
    dest: /etc/systemd/system/kube-apiserver.service
    mode: 644

- name: Create Kubernetes Controller Manager systemd unit file
  template:
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
    mode: 644

- name: Create Kubernetes Scheduler config file
  template:
    src: kube-scheduler.yaml.j2
    dest: /etc/kubernetes/config/kube-scheduler.yaml
    mode: 644

- name: Create Kubernetes Scheduler systemd unit file
  template:
    src: kube-scheduler.service.j2
    dest: /etc/systemd/system/kube-scheduler.service
    mode: 644

- name: Restart Controller Services
  systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: yes
    enabled: yes
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- name: Wait for 20 seconds to controller services start
  pause:
    seconds: 20

- name: Create ClusterRole to access the Kubelet API
  command: kubectl apply --kubeconfig admin.kubeconfig -f -
  args:
    stdin: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: system:kube-apiserver
        namespace: ""
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: system:kube-apiserver-to-kubelet
      subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: User
          name: kubernetes
  run_once: true
  register: clusterRole

- debug:
    var: clusterRole.stdout

- name: Bind the system:kube-apiserver-to-kubelet ClusterRole to the kubernetes user
  command: kubectl apply --kubeconfig admin.kubeconfig -f -
  args:
    stdin: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: system:kube-apiserver
        namespace: ""
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: system:kube-apiserver-to-kubelet
      subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: User
          name: kubernetes
  run_once: true

- name: Set lb_IP variable
  set_fact:
    lb_IP: "{{ hostvars[item].external_ip }}"
  when: hostvars[item].loadbalancer is defined
  with_items: "{{ groups['all'] }}"
  loop_control:
    label: "{{ item }}"

- name: Configuring kubectl for Remote Access
  shell: |
    kubectl config set-cluster kubernetes-the-hard-way \
    --certificate-authority=ca.pem \
    --embed-certs=true \
    --server=https://"{{ lb_IP }}":6443
    kubectl config set-credentials admin \
    --client-certificate=admin.pem \
    --client-key=admin-key.pem
    kubectl config set-context kubernetes-the-hard-way \
    --cluster=kubernetes-the-hard-way \
    --user=admin
    kubectl config use-context kubernetes-the-hard-way    
