---
- name: Copy etcd binary files
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    mode: 0744
    remote_src: yes
  with_items:
    - /tmp/etcd-{{ kubernetes.etcdVersion }}/etcd
    - /tmp/etcd-{{ kubernetes.etcdVersion }}/etcdctl
    - /tmp/etcd-{{ kubernetes.etcdVersion }}/etcdutl

- name: Create /etc/etcd and /var/lib/etcd directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  loop:
    - /etc/etcd
    - /var/lib/etcd

- name: Copy files to /etc/etcd
  copy:
    src: "{{ item }}"
    dest: /etc/etcd/
    remote_src: yes
  with_items:
    - /tmp/ca.pem
    - /tmp/kubernetes-key.pem
    - /tmp/kubernetes.pem

- name: Create etcd systemd unit file
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: 0644

- name: Restart etcd
  systemd:
    name: etcd
    state: restarted
    daemon_reload: yes
    enabled: yes
