---
- name: Generate kubeconfig for workers
  args:
    chdir: "{{ kubernetes.certificate.directory }}"
  shell: |
    kubectl config set-cluster {{ kubernetes.clusterName }} \
      --certificate-authority=ca.pem \
      --embed-certs=true \
      --server=https://{{ kubernetes.clusterName }}:6443 \
      --kubeconfig={{ item }}.kubeconfig

    kubectl config set-credentials system:node:{{ item }} \
      --client-certificate={{ item }}.pem \
      --client-key={{ item }}-key.pem \
      --embed-certs=true \
      --kubeconfig={{ item }}.kubeconfig

    kubectl config set-context default \
      --cluster={{ kubernetes.clusterName }} \
      --user=system:node:{{ item }} \
      --kubeconfig={{ item }}.kubeconfig

    kubectl config use-context default --kubeconfig={{ item }}.kubeconfig
  with_items: "{{ groups['worker'] }}"

- name: Generate kubeconfig for kube-controller-manager
  args:
    chdir: "{{ kubernetes.certificate.directory }}"
  shell: |
    kubectl config set-cluster {{ kubernetes.clusterName }} \
      --certificate-authority=ca.pem \
      --embed-certs=true \
      --server=https://{{ kubernetes.clusterName }}:6443 \
      --kubeconfig=kube-controller-manager.kubeconfig

    kubectl config set-credentials system:kube-controller-manager \
      --client-certificate=kube-controller-manager.pem \
      --client-key=kube-controller-manager-key.pem \
      --embed-certs=true \
      --kubeconfig=kube-controller-manager.kubeconfig

    kubectl config set-context default \
      --cluster={{ kubernetes.clusterName }} \
      --user=system:kube-controller-manager \
      --kubeconfig=kube-controller-manager.kubeconfig

    kubectl config use-context default --kubeconfig=kube-controller-manager.kubeconfig  

- name: Generate kubeconfig for kube-scheduler
  args:
    chdir: "{{ kubernetes.certificate.directory }}"
  shell: |
    kubectl config set-cluster {{ kubernetes.clusterName }} \
      --certificate-authority=ca.pem \
      --embed-certs=true \
      --server=https://{{ kubernetes.clusterName }}:6443 \
      --kubeconfig=kube-scheduler.kubeconfig

    kubectl config set-credentials system:kube-scheduler \
      --client-certificate=kube-scheduler.pem \
      --client-key=kube-scheduler-key.pem \
      --embed-certs=true \
      --kubeconfig=kube-scheduler.kubeconfig

    kubectl config set-context default \
      --cluster={{ kubernetes.clusterName }} \
      --user=system:kube-scheduler \
      --kubeconfig=kube-scheduler.kubeconfig

    kubectl config use-context default --kubeconfig=kube-scheduler.kubeconfig  


- name: Generate kubeconfig for admin
  args:
    chdir: "{{ kubernetes.certificate.directory }}"
  shell: |
    kubectl config set-cluster {{ kubernetes.clusterName }} \
      --certificate-authority=ca.pem \
      --embed-certs=true \
      --server=https://{{ kubernetes.clusterName }}:6443 \
      --kubeconfig=admin.kubeconfig

    kubectl config set-credentials admin \
      --client-certificate=admin.pem \
      --client-key=admin-key.pem \
      --embed-certs=true \
      --kubeconfig=admin.kubeconfig

    kubectl config set-context default \
      --cluster={{ kubernetes.clusterName }} \
      --user=admin \
      --kubeconfig=admin.kubeconfig

    kubectl config use-context default --kubeconfig=admin.kubeconfig
