---
- name: Copy certs into worker nodes
  copy:
    src: "{{item}}"
    dest: /tmp
    owner: root
    group: root
    mode: 0644
  loop:
    - "{{ kubernetes.certificate.directory }}/ca.pem"
    - "{{ kubernetes.certificate.directory }}/{{ inventory_hostname }}.pem"
    - "{{ kubernetes.certificate.directory }}/{{ inventory_hostname }}-key.pem"
    - "{{ kubernetes.certificate.directory }}/{{ inventory_hostname }}.kubeconfig"

- name: Copy worker binaries to worker nodes
  copy: 
    src: "{{ item.src }}" 
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0744
  loop:
    - src: "{{ kubernetes.bin.directory }}/{{ kubernetes.version }}/kubelet"
      dest: "/tmp/{{ kubernetes.version }}/"
    - src: "{{ kubernetes.bin.directory }}/nerdctl-{{ kubernetes.nerdctlVersion }}/nerdctl"
      dest: "/tmp/nerdctl-{{ kubernetes.nerdctlVersion }}/"
    - src: "{{ kubernetes.bin.directory }}/runc-{{ kubernetes.runcVersion }}/runc"
      dest: "/tmp/runc-{{ kubernetes.runcVersion }}/"
    - src: "{{ kubernetes.bin.directory }}/containerd-{{ kubernetes.containerdVersion }}/"
      dest: "/tmp/containerd-{{ kubernetes.containerdVersion }}/"
    - src: "{{ kubernetes.bin.directory }}/cni-{{ kubernetes.cniVersion }}/"
      dest: "/tmp/cni-{{ kubernetes.cniVersion }}/"

