---
- name: Add vip dns name to /etc/hosts
  shell: |
    grep -q "{{ kubernetes.clusterName }}" /etc/hosts || echo "{{ kubernetes.network.vip }} {{ kubernetes.clusterName }}" >> /etc/hosts

- name: Add kernel modules to /etc/modules-load.d/k8s.conf
  shell: |
    grep -q "overlay" /etc/modules-load.d/k8s.conf || echo "overlay" >> /etc/modules-load.d/k8s.conf
    grep -q "br_netfilter" /etc/modules-load.d/k8s.conf || echo "br_netfilter" >> /etc/modules-load.d/k8s.conf
    grep -q "iptable_filter" /etc/modules-load.d/k8s.conf || echo "iptable_filter" >> /etc/modules-load.d/k8s.conf
    grep -q "iptable_nat" /etc/modules-load.d/k8s.conf || echo "iptable_nat" >> /etc/modules-load.d/k8s.conf
    grep -q "iptable_mangle" /etc/modules-load.d/k8s.conf || echo "iptable_mangle" >> /etc/modules-load.d/k8s.conf
    modprobe overlay
    modprobe br_netfilter
    modprobe iptable_filter
    modprobe iptable_nat
    modprobe iptable_mangle

- name: Add sysctl parameters to /etc/sysctl.d/k8s.conf
  shell: |
    grep -q "net.bridge.bridge-nf-call-iptables" /etc/sysctl.d/k8s.conf || echo "net.bridge.bridge-nf-call-iptables = 1" >> /etc/sysctl.d/k8s.conf
    grep -q "net.bridge.bridge-nf-call-ip6tables" /etc/sysctl.d/k8s.conf || echo "net.bridge.bridge-nf-call-ip6tables = 1" >> /etc/sysctl.d/k8s.conf
    grep -q "net.ipv4.ip_forward" /etc/sysctl.d/k8s.conf || echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.d/k8s.conf
    sysctl --system
