---
- name: Prepare calico config
  template:
    src: kube-calico.yml.j2
    dest: ~/kube-calico.yml
    mode: 644
  run_once: true

- name: Deploy calico in cluster
  shell: |
    kubectl delete -f ~/kube-calico.yml
    kubectl apply -f ~/kube-calico.yml
  run_once: true

