---
- name: Deploy nginx ingress controller 
  shell: |
    helm upgrade --install ingress-nginx ingress-nginx \
    --repo https://kubernetes.github.io/ingress-nginx \
    --namespace ingress-nginx --create-namespace \
    --set controller.hostNetwork=true,controller.service.type="",controller.kind=DaemonSet
  run_once: true

