---
- name: Copy kubeconfigs into worker nodes
  vars:
    workers: "{{ groups['worker'] | join(' ') }}"
  args:
    chdir: "{{ kubernetes.certificate.directory }}"
  shell: |
    for instance in {{ workers }}; do
      scp ${instance}.kubeconfig {{ user }}@${instance}:~/${instance}.kubeconfig
      scp kube-proxy.kubeconfig {{ user }}@${instance}:~/kube-proxy.kubeconfig
    done
  tags:
    - copy_kubeconfigs

- name: Copy kubeconfigs into controller nodes
  vars:
    controllers: "{{ groups['controller'] | join(' ') }}"
  args:
    chdir: "{{ kubernetes.certificate.directory }}"
  shell: |
    for instance in {{ controllers }}; do
      scp admin.kubeconfig {{ user }}@${instance}:~/admin.kubeconfig
      scp kube-controller-manager.kubeconfig {{ user }}@${instance}:~/kube-controller-manager.kubeconfig
      scp kube-scheduler.kubeconfig {{ user }}@${instance}:~/kube-scheduler.kubeconfig
    done
  tags:
    - copy_kubeconfigs
