---
- name: Copy certs into worker nodes
  shell: |
    scp -o StrictHostKeyChecking=no ca.pem {{ item }}.pem {{ item }}-key.pem {{ ansible_ssh_user }}@{{ hostvars[item].ansible_host }}:/tmp
  with_items: "{{ groups['worker'] }}"
  args:
    chdir: "{{ kubernetes.certificate.directory }}"

- name: Copy certs into controller nodes
  shell: |
    scp -o StrictHostKeyChecking=no ca.pem ca-key.pem admin.pem admin-key.pem {{ ansible_ssh_user }}@{{ hostvars[item].ansible_host }}:/tmp
    scp -o StrictHostKeyChecking=no kubernetes.pem kubernetes-key.pem {{ ansible_ssh_user }}@{{ hostvars[item].ansible_host }}:/tmp
    scp -o StrictHostKeyChecking=no service-account.pem service-account-key.pem {{ ansible_ssh_user }}@{{ hostvars[item].ansible_host }}:/tmp
  with_items: "{{ groups['controller'] }}"
  args:
    chdir: "{{ kubernetes.certificate.directory }}"
